version: '3'

services:
  api-veterniaria:
    build: api-veterniaria
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://clinica_vet:3306/api_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: ""  # Deja esto vacío ya que no estás utilizando contraseña
    restart: always
    depends_on:
      clinica_vet:
        condition: service_healthy

  clinica_vet:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permite el uso de contraseña vacía
      MYSQL_DATABASE: api_veterinaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
